import { useEffect, useState } from "react";

const API_BASE = "https://peizo-backend.onrender.com";

export default function App() {
  const [stats, setStats] = useState(null);
  const [form, setForm] = useState({
    voltage: "",
    current_uA: "",
    weight_kg: "",
    step_location: "Center",
  });
  const [prediction, setPrediction] = useState(null);

  useEffect(() => {
    async function loadStats() {
      try {
        const res = await fetch(`${API_BASE}/stats`);
        const json = await res.json();
        setStats(json);
      } catch (err) {
        console.error("Error loading stats:", err);
      }
    }
    loadStats();
  }, []);

  async function handlePredict(e) {
    e.preventDefault();
    try {
      const res = await fetch(`${API_BASE}/predict`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          voltage: parseFloat(form.voltage),
          current_uA: parseFloat(form.current_uA),
          weight_kg: parseFloat(form.weight_kg),
          step_location: form.step_location,
        }),
      });

      const json = await res.json();
      if (json?.predicted_power_mW != null) {
        setPrediction(json.predicted_power_mW.toFixed(3));
      }
    } catch (err) {
      console.error("Prediction error:", err);
    }
  }

  const avgPower = stats?.avg_power ?? 0;
  const maxPower = stats?.max_power ?? 1;
  const gaugeRatio = Math.max(0, Math.min(1, maxPower ? avgPower / maxPower : 0));

  return (
    <div style={pageStyle}>
      <header
  style={{
    padding: "18px 32px 10px",
    borderBottom: "1px solid rgba(16,185,129,0.25)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backdropFilter: "blur(14px)",
    background:
      "linear-gradient(90deg,rgba(6,78,59,0.9),rgba(5,46,22,0.95))",
    boxShadow: "0 18px 40px rgba(0,0,0,0.4)",
    position: "sticky",
    top: 0,
    zIndex: 20,
  }}
>
  <div>
    <div
      style={{
        fontSize: 13,
        letterSpacing: 2,
        textTransform: "uppercase",
        color: "#6ee7b7",
        marginBottom: 2,
      }}
    >
      🌍 Sustainability · ⚡ Smart Energy
    </div>
    <h1 style={{ margin: 0, fontSize: 26, fontWeight: 700 }}>
      Piezoelectric Smart Tile Dashboard
    </h1>
    <p style={{ margin: "3px 0 0", fontSize: 12, color: "#a7f3d0" }}>
      AI-powered prediction of renewable energy from footsteps.
    </p>
  </div>

  <div
    style={{
      padding: "6px 12px",
      background: "rgba(6,95,70,0.4)",
      borderRadius: 12,
      border: "1px solid rgba(52,211,153,0.6)",
      color: "#a7f3d0",
      fontSize: 12,
    }}
  >
    🔌 Backend: Render (Live)
  </div>
</header>


      <main style={mainStyle}>
       <HoverCard style={overviewStyle}>
  <div>
    <h2 style={{ marginTop: 0, fontSize: 22, display: "flex", gap: 8 }}>
      ♻️ Project Overview
    </h2>
    <p style={{ fontSize: 14, opacity: 0.9 }}>
      This dashboard visualises energy generated by piezoelectric floor tiles.
      The ML model predicts power output per footstep using{" "}
      <b>weight</b>, <b>voltage</b>, <b>current</b> and{" "}
      <b>step location</b>.
    </p>
    <ul style={{ fontSize: 14, opacity: 0.9, marginTop: 10 }}>
      <li>⚡ Instant prediction of power for any step</li>
      <li>🚶 Helps decide where tiles should be installed</li>
      <li>🏫 Supports sustainable smart-campus design</li>
    </ul>
  </div>

  <div
    style={{
      display: "flex",
      gap: 18,
      justifyContent: "flex-end",
      alignItems: "center",
      flexWrap: "wrap",
    }}
  >
    {/* Gauge */}
    <div
      style={{
        width: 110,
        height: 110,
        borderRadius: "50%",
        background: "radial-gradient(circle at 30% 30%,#22c55e33,#020617)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
      }}
    >
      <svg width="90" height="90" viewBox="0 0 36 36">
        <path
          d="M18 2 a 16 16 0 1 1 0 32 a 16 16 0 1 1 0 -32"
          fill="none"
          stroke="#1f2937"
          strokeWidth="3.2"
        />
        <path
          d="M18 2 a 16 16 0 1 1 0 32 a 16 16 0 1 1 0 -32"
          fill="none"
          stroke="#22c55e"
          strokeWidth="3.2"
          strokeDasharray={`${100 * gaugeRatio}, 100`}
          strokeLinecap="round"
        />
      </svg>
      <div style={{ position: "absolute", textAlign: "center", fontSize: 11 }}>
        <div style={{ fontSize: 10, color: "#9ca3af" }}>Avg Power</div>
        <div style={{ fontSize: 16, fontWeight: 700 }}>
          {stats?.avg_power != null ? stats.avg_power.toFixed(2) : "--"} mW
        </div>
      </div>
    </div>

    <img
      src="/piezo-tile.jpg"
      alt="Piezoelectric Tile"
      style={{
        width: 220,
        height: 120,
        objectFit: "cover",
        borderRadius: 16,
        boxShadow: "0 0 16px rgba(16,185,129,0.6)",
        border: "1px solid rgba(148,163,184,0.7)",
      }}
    />
  </div>
</HoverCard>

        <section style={statsGrid}>
          <StatCard label="Total Readings" value={stats?.count ?? "--"} icon="📊" />
          <StatCard label="Average Power (mW)" value={stats?.avg_power?.toFixed(2) ?? "--"} icon="⚡" />
          <StatCard label="Max Power (mW)" value={stats?.max_power?.toFixed(2) ?? "--"} icon="🚀" />
          <StatCard label="Min Power (mW)" value={stats?.min_power?.toFixed(2) ?? "--"} icon="🔋" />
        </section>

        <section style={{ display: "grid", gridTemplateColumns: "1.5fr 1fr", gap: 20 }}>
          <HoverCard style={graphStyle}>
            <h3>📈 Energy Output vs People</h3>
            <p style={graphDesc}>
              Graph showing how energy output varies as more people step on the tiles.
            </p>
            <img
              src="/energy-output-vs-people.png"
              alt="Energy Output vs People"
              style={graphImg}
            />
          </HoverCard>

          <PredictPanel
            form={form}
            setForm={setForm}
            handlePredict={handlePredict}
            prediction={prediction}
          />
        </section>
      </main>
    </div>
  );
}

/* ---------- COMPONENTS ---------- */

function HoverCard({ children, style }) {
  const [hover, setHover] = useState(false);

  return (
    <div
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        ...style,
        transform: hover ? "translateY(-6px)" : "none",
        boxShadow: hover
          ? "0 25px 60px rgba(16,185,129,0.45)"
          : style.boxShadow,
        transition: "all 0.25s ease",
      }}
    >
      {children}
    </div>
  );
}

function StatCard({ label, value, icon }) {
  const [hover, setHover] = useState(false);

  return (
    <div
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        ...statCardStyle,
        transform: hover ? "translateY(-6px) scale(1.02)" : "none",
        boxShadow: hover
          ? "0 30px 70px rgba(16,185,129,0.55)"
          : statCardStyle.boxShadow,
        transition: "all 0.25s ease",
      }}
    >
      <div style={{ fontSize: 13, color: "#a7f3d0" }}>
        {label} <span style={{ float: "right" }}>{icon}</span>
      </div>
      <div style={{ fontSize: 28, fontWeight: 700 }}>{value}</div>
    </div>
  );
}

function PredictPanel({ form, setForm, handlePredict, prediction }) {
  return (
    <HoverCard style={predictStyle}>
      <form onSubmit={handlePredict}>
        <h3>🤖 Predict Power Output</h3>

        <Input label="Voltage (V)" value={form.voltage} onChange={(v) => setForm({ ...form, voltage: v })} />
        <Input label="Current (µA)" value={form.current_uA} onChange={(v) => setForm({ ...form, current_uA: v })} />
        <Input label="Weight (kg)" value={form.weight_kg} onChange={(v) => setForm({ ...form, weight_kg: v })} />

        <label>
          Step Location
          <select
            value={form.step_location}
            onChange={(e) => setForm({ ...form, step_location: e.target.value })}
            style={selectStyle}
          >
            <option value="Center">Center</option>
            <option value="Edge">Edge</option>
            <option value="Corner">Corner</option>
          </select>
        </label>

        <HoverButton />

        {prediction && (
          <p style={predictionStyle}>
            🔋 Predicted Power: {prediction} mW
          </p>
        )}
      </form>
    </HoverCard>
  );
}

function HoverButton() {
  const [hover, setHover] = useState(false);

  return (
    <button
      type="submit"
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        ...buttonStyle,
        transform: hover ? "scale(1.05)" : "scale(1)",
        boxShadow: hover
          ? "0 0 30px rgba(34,197,94,0.9)"
          : buttonStyle.boxShadow,
        transition: "all 0.2s ease",
      }}
    >
      🔍 Predict
    </button>
  );
}

function Input({ label, value, onChange }) {
  return (
    <label>
      {label}
      <input
        required
        type="number"
        step="0.01"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        style={inputStyle}
      />
    </label>
  );
}

/* ---------- STYLES (UNCHANGED) ---------- */

const pageStyle = {
  minHeight: "100vh",
  background:
    "radial-gradient(circle at top, #16a34a22, #000000), linear-gradient(135deg,#022c22,#020617)",
  color: "#e5ffe9",
  fontFamily: "system-ui",
};

const mainStyle = { padding: 32, maxWidth: 1400, margin: "0 auto" };

const overviewStyle = {
  padding: 20,
  borderRadius: 22,
  background:
    "linear-gradient(145deg,rgba(5,46,22,0.95),rgba(16,185,129,0.15))",
  border: "1px solid rgba(52,211,153,0.5)",
  marginBottom: 24,
  boxShadow: "0 18px 40px rgba(0,0,0,0.4)",
};

const statsGrid = {
  display: "grid",
  gridTemplateColumns: "repeat(4, 1fr)",
  gap: 16,
  marginBottom: 24,
};

const statCardStyle = {
  padding: 16,
  borderRadius: 18,
  background:
    "linear-gradient(145deg,rgba(15,23,42,0.95),rgba(16,185,129,0.18))",
  border: "1px solid rgba(52,211,153,0.7)",
  boxShadow: "0 18px 40px rgba(0,0,0,0.85)",
};

const graphStyle = {
  padding: 20,
  borderRadius: 22,
  background:
    "linear-gradient(145deg,rgba(5,46,22,0.95),rgba(16,185,129,0.12))",
  border: "1px solid rgba(52,211,153,0.5)",
  boxShadow: "0 18px 40px rgba(0,0,0,0.6)",
};

const graphImg = {
  width: "100%",
  marginTop: 12,
  borderRadius: 12,
  boxShadow: "0 0 20px rgba(16,185,129,0.4)",
};

const graphDesc = { fontSize: 12, color: "#9ca3af", marginTop: 4 };

const predictStyle = {
  padding: 22,
  borderRadius: 22,
  background:
    "linear-gradient(145deg,rgba(5,46,22,0.95),rgba(16,185,129,0.12))",
  border: "1px solid rgba(52,211,153,0.5)",
  boxShadow: "0 18px 40px rgba(0,0,0,0.6)",
};

const inputStyle = {
  width: "100%",
  padding: 8,
  marginTop: 4,
  marginBottom: 10,
  borderRadius: 10,
  border: "1px solid rgba(52,211,153,0.9)",
  background: "#020617",
  color: "#e5ffe9",
};

const selectStyle = { ...inputStyle };

const buttonStyle = {
  marginTop: 10,
  padding: "9px 14px",
  borderRadius: 999,
  border: "none",
  background: "linear-gradient(135deg, #22c55e, #4ade80, #22c55e)",
  color: "#022c22",
  fontWeight: 700,
  fontSize: 14,
  cursor: "pointer",
  width: "100%",
  boxShadow: "0 14px 30px rgba(22,163,74,0.7)",
};

const predictionStyle = {
  marginTop: 12,
  fontWeight: 700,
  fontSize: 18,
  textAlign: "center",
};
