import { useEffect, useState } from "react";

/* ================= CONFIG ================= */

const API_BASE = "https://peizo-backend.onrender.com";

const colors = {
  bg: "#020617",
  glass: "rgba(255,255,255,0.06)",
  border: "rgba(255,255,255,0.12)",
  text: "#e5e7eb",
  muted: "#9ca3af",
  accent: "#22c55e",
};

/* ================= APP ================= */

export default function App() {
  const [stats, setStats] = useState(null);
  const [form, setForm] = useState({
    voltage: "",
    current_uA: "",
    weight_kg: "",
    step_location: "Center",
  });
  const [prediction, setPrediction] = useState(null);

  useEffect(() => {
    async function loadStats() {
      try {
        const res = await fetch(`${API_BASE}/stats`);
        const json = await res.json();
        setStats(json);
      } catch (err) {
        console.error("Error loading stats:", err);
      }
    }
    loadStats();
  }, []);

  async function handlePredict(e) {
    e.preventDefault();
    try {
      const res = await fetch(`${API_BASE}/predict`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          voltage: parseFloat(form.voltage),
          current_uA: parseFloat(form.current_uA),
          weight_kg: parseFloat(form.weight_kg),
          step_location: form.step_location,
        }),
      });

      const json = await res.json();
      if (json?.predicted_power_mW != null) {
        setPrediction(json.predicted_power_mW.toFixed(3));
      }
    } catch (err) {
      console.error("Prediction error:", err);
    }
  }

  return (
    <div style={pageStyle}>
      {/* ========== HEADER ========== */}
      <header style={headerStyle}>
        <div>
          <div style={headerTag}>⚡ Smart Energy · AI Dashboard</div>
          <h1 style={headerTitle}>Piezoelectric Smart Tile</h1>
          <p style={headerSub}>
            Predict renewable energy generation from footsteps using ML
          </p>
        </div>
        <div style={headerBadge}>Backend: Live</div>
      </header>

      {/* ========== MAIN ========== */}
      <main style={mainStyle}>
        {/* HERO */}
        <GlassCard style={heroStyle}>
          <div>
            <h2 style={heroTitle}>AI-Powered Energy Prediction</h2>
            <p style={heroText}>
              This system estimates power generated by piezoelectric tiles based
              on real-world step parameters like weight, voltage and impact
              location.
            </p>
            <ul style={heroList}>
              <li>⚡ Real-time prediction per footstep</li>
              <li>🏫 Smart campus & public infrastructure planning</li>
              <li>♻️ Supports sustainable energy decisions</li>
            </ul>
          </div>

          <div style={heroMetric}>
            <div style={heroMetricLabel}>Average Power</div>
            <div style={heroMetricValue}>
              {stats?.avg_power != null
                ? stats.avg_power.toFixed(2)
                : "--"}{" "}
              mW
            </div>
          </div>
        </GlassCard>

        {/* STATS */}
        <section style={statsGrid}>
          <Stat label="Total Readings" value={stats?.count ?? "--"} />
          <Stat
            label="Avg Power (mW)"
            value={stats?.avg_power?.toFixed(2) ?? "--"}
          />
          <Stat
            label="Max Power (mW)"
            value={stats?.max_power?.toFixed(2) ?? "--"}
          />
          <Stat
            label="Min Power (mW)"
            value={stats?.min_power?.toFixed(2) ?? "--"}
          />
        </section>

        {/* CONTENT */}
        <section style={contentGrid}>
          <GlassCard>
            <h3 style={sectionTitle}>Energy Output vs People</h3>
            <p style={sectionDesc}>
              Relationship between number of footsteps and generated energy.
            </p>
            <img
              src="/energy-output-vs-people.png"
              alt="Energy graph"
              style={graphImg}
            />
          </GlassCard>

          <GlassCard>
            <form onSubmit={handlePredict}>
              <h3 style={sectionTitle}>Predict Power Output</h3>

              <Input
                label="Voltage (V)"
                value={form.voltage}
                onChange={(v) => setForm({ ...form, voltage: v })}
              />
              <Input
                label="Current (µA)"
                value={form.current_uA}
                onChange={(v) => setForm({ ...form, current_uA: v })}
              />
              <Input
                label="Weight (kg)"
                value={form.weight_kg}
                onChange={(v) => setForm({ ...form, weight_kg: v })}
              />

              <label style={labelStyle}>
                Step Location
                <select
                  value={form.step_location}
                  onChange={(e) =>
                    setForm({ ...form, step_location: e.target.value })
                  }
                  style={inputStyle}
                >
                  <option value="Center">Center</option>
                  <option value="Edge">Edge</option>
                  <option value="Corner">Corner</option>
                </select>
              </label>

              <button type="submit" style={buttonStyle}>
                Predict
              </button>

              {prediction && (
                <div style={predictionBox}>
                  🔋 {prediction} mW predicted
                </div>
              )}
            </form>
          </GlassCard>
        </section>
      </main>
    </div>
  );
}

/* ================= COMPONENTS ================= */

function GlassCard({ children, style }) {
  return (
    <div style={{ ...glassCard, ...style }}>
      {children}
    </div>
  );
}

function Stat({ label, value }) {
  return (
    <div style={statCard}>
      <div style={statLabel}>{label}</div>
      <div style={statValue}>{value}</div>
    </div>
  );
}

function Input({ label, value, onChange }) {
  return (
    <label style={labelStyle}>
      {label}
      <input
        required
        type="number"
        step="0.01"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        style={inputStyle}
      />
    </label>
  );
}

/* ================= STYLES ================= */

const pageStyle = {
  minHeight: "100vh",
  background:
    "radial-gradient(circle at top, rgba(34,197,94,0.15), transparent 40%), #020617",
  color: colors.text,
  fontFamily: "Inter, system-ui",
};

const headerStyle = {
  padding: "20px 32px",
  position: "sticky",
  top: 0,
  zIndex: 10,
  backdropFilter: "blur(20px)",
  background: "rgba(2,6,23,0.6)",
  borderBottom: `1px solid ${colors.border}`,
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
};

const headerTag = {
  fontSize: 12,
  letterSpacing: 2,
  textTransform: "uppercase",
  color: colors.accent,
};

const headerTitle = { margin: 0, fontSize: 26, fontWeight: 700 };

const headerSub = { marginTop: 4, fontSize: 13, color: colors.muted };

const headerBadge = {
  padding: "6px 12px",
  borderRadius: 999,
  fontSize: 12,
  background: colors.glass,
  border: `1px solid ${colors.border}`,
};

const mainStyle = {
  maxWidth: 1400,
  margin: "0 auto",
  padding: 32,
};

const glassCard = {
  background: colors.glass,
  backdropFilter: "blur(18px)",
  border: `1px solid ${colors.border}`,
  borderRadius: 20,
  padding: 20,
};

const heroStyle = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: 28,
};

const heroTitle = { fontSize: 24, fontWeight: 700 };

const heroText = { fontSize: 14, color: colors.muted, marginTop: 6 };

const heroList = {
  marginTop: 12,
  fontSize: 14,
  color: colors.text,
};

const heroMetric = { textAlign: "right" };

const heroMetricLabel = { fontSize: 12, color: colors.muted };

const heroMetricValue = {
  fontSize: 32,
  fontWeight: 800,
  color: colors.accent,
};

const statsGrid = {
  display: "grid",
  gridTemplateColumns: "repeat(4,1fr)",
  gap: 16,
  marginBottom: 28,
};

const statCard = {
  padding: 18,
  borderRadius: 18,
  background: colors.glass,
  border: `1px solid ${colors.border}`,
};

const statLabel = { fontSize: 12, color: colors.muted };

const statValue = { fontSize: 26, fontWeight: 700 };

const contentGrid = {
  display: "grid",
  gridTemplateColumns: "1.4fr 1fr",
  gap: 20,
};

const sectionTitle = { marginBottom: 4, fontSize: 18, fontWeight: 600 };

const sectionDesc = { fontSize: 12, color: colors.muted };

const graphImg = {
  width: "100%",
  borderRadius: 14,
  marginTop: 12,
};

const labelStyle = {
  display: "block",
  fontSize: 13,
  marginBottom: 10,
};

const inputStyle = {
  width: "100%",
  padding: 9,
  marginTop: 4,
  borderRadius: 10,
  border: `1px solid ${colors.border}`,
  background: "#020617",
  color: colors.text,
};

const buttonStyle = {
  width: "100%",
  marginTop: 12,
  padding: "10px",
  borderRadius: 999,
  border: "none",
  background: colors.accent,
  fontWeight: 700,
  cursor: "pointer",
};

const predictionBox = {
  marginTop: 14,
  padding: 14,
  borderRadius: 14,
  background: "linear-gradient(135deg,#22c55e22,#22c55e11)",
  textAlign: "center",
  fontSize: 18,
  fontWeight: 700,
};
